<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 4.1.2 Linear Regression

In Lab 4.1.1 we were able to predict house price via a predictor variable from first principles. Here we the see how the same can be done using scikit-learn.

For comparison purposes, we will continue with the same predictor `sq__ft` in our dataset as last time.

## Prediction of House Price Using Linear Regression

### Data

The Sacramento real estate transactions file is a list of 985 real estate transactions in the Sacramento area reported over a five-day period, as reported by the Sacramento Bee.

In [1]:
import pandas as pd
import numpy as np
import pandas as pd

%matplotlib inline

### 1. Read in the data

In [3]:
# Read CSV
house_csv = "../DATA/Sacramento_transactions.csv"
data = pd.read_csv(house_csv)
data.head()

street        city    zip state  beds  baths  sq__ft  \
0      3526 HIGH ST  SACRAMENTO  95838    CA     2      1     836   
1       51 OMAHA CT  SACRAMENTO  95823    CA     3      1    1167   
2    2796 BRANCH ST  SACRAMENTO  95815    CA     2      1     796   
3  2805 JANETTE WAY  SACRAMENTO  95815    CA     2      1     852   
4   6001 MCMAHON DR  SACRAMENTO  95824    CA     2      1     797   

          type                     sale_date  price   latitude   longitude  
0  Residential  Wed May 21 00:00:00 EDT 2008  59222  38.631913 -121.434879  
1  Residential  Wed May 21 00:00:00 EDT 2008  68212  38.478902 -121.431028  
2  Residential  Wed May 21 00:00:00 EDT 2008  68880  38.618305 -121.443839  
3  Residential  Wed May 21 00:00:00 EDT 2008  69307  38.616835 -121.439146  
4  Residential  Wed May 21 00:00:00 EDT 2008  81900  38.519470 -121.435768

### 2. Predict Price

We are going to predict the target variable `price` from `sq__ft` using sklearn's linear_model.

Read up on the following methods and attributes here: [sklearn.linear_model.LinearRegression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html)

- coef_
- intercept_
- fit()
- predict()
- score()

In [6]:
# import the LinearRegression class from the sklearn.linear_model module
from sklearn.linear_model import LinearRegression

#### 2.1 Create an instance of LinearRegression.

In [7]:
# ANSWER
linreg = LinearRegression()

#### 2.2 Fit predictor and target variables using linear regression

In [40]:
X = data['sq__ft'].values.reshape(-1,1)  # --> Convert to list (?)
y = data['price']

type(y)

pandas.core.series.Series

In [18]:
# ANSWER
linreg.fit(X, y)

LinearRegression()

#### 2.3. Using attributes of the LinearRegression() class find coefficient and intercept.

In [19]:
# ANSWER
linreg.coef_


array([54.15863969])

In [20]:
linreg.intercept_

162930.16140699777

#### 2.4 Find R^2 Score

Find $R^2$ Using the ```score``` method of LinearRegression.

In [21]:
# ANSWER
linreg.score(X, y)

0.11148717682951437

### 3. Splitting Data


Splitting the data into training and test sets is important in supervised learning.

- We ensure that the test set remains untouched during the model training process. This isolation prevents any information leakage about the test set into the training process.

- It allows us to evaluate the performance of our machine learning model on unseen data.


In [16]:
from sklearn.model_selection import train_test_split

#### 3.1 Create training and testing subsets

Hint: Use the `train_test_split` Library.

```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
```

In [22]:
# ANSWER
## Create training and testing subsets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

#### 3.2 Check Shape, Sample of Test Train Data

In [23]:
# ANSWER
## Check training/test data

X_train.shape

(659, 1)

In [24]:
X_test.shape

(326, 1)

In [25]:
y_train.shape

(659,)

In [26]:
y_test.shape

(326,)

#### 3.3 Using Linear Regression Find The Score

1. Fit model using X_train, y_train
2. Find score using X_test, y_test

In [27]:
# ANSWER
linreg1 = LinearRegression()

In [28]:
linreg1.fit(X_train, y_train)

LinearRegression()

In [33]:
# ANSWER
linreg1.coef_

array([47.43508406])

In [34]:
linreg1.intercept_

166482.3414496886

In [35]:
linreg1.score(X_train, y_train)

0.08614711011567588

### 4. Predict House Price

Let's assume we have information of following house:

- street:	1140 EDMONTON DR
- city:	SACRAMENTO
- zip:	95833
- state:	CA
- beds:	3
- baths:	2
- sq__ft:	1204
- type:	Residential

**Predict the price of this house using the linear regression model.**

In [36]:
# ANSWER
slope = linreg1.coef_
intercept = linreg1.intercept_

predicted_price = intercept + slope * 1204
predicted_price

array([223594.18266381])

#### Find the error

In [ ]:
# Predict price from X_test

### Conclusion
We have seen that through scikit-learn, minimal code is needed to implement and evaluate a linear regression model.

# Part 2: Repeat, with residential only & sq__ft > 0

Use X = `sq__ft` * `bdrm`

In [37]:
res_gt0 = data[(data.sq__ft > 0) & (data.type == "Residential") ]
res_gt0.shape

(759, 12)

In [47]:
x = (res_gt0.sq__ft * res_gt0.beds).values.reshape(-1,1)
y = res_gt0.price

print(type(x), type(y))

<class 'numpy.ndarray'> <class 'pandas.core.series.Series'>


In [48]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)


(508, 1) (251, 1)
(508,) (251,)


In [49]:
linreg_resgt0 = LinearRegression()
linreg_resgt0.fit(x_train, y_train)


LinearRegression()

In [50]:
linreg_resgt0.score(x_train, y_train)

0.39711909727045835

In [54]:
slope = linreg_resgt0.coef_
intercept = linreg_resgt0.intercept_
predicted_price_new = intercept + slope * 1204

print(f'Previously predicted price: {predicted_price[0]}')
print(f'New predicted price: {predicted_price_new[0]}')

Previously predicted price: 223594.18266380776
New predicted price: 139552.45534691776




---



---



> > > > > > > > > © 2024 Institute of Data


---



---



